cfehome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView
from chat import views

urlpatterns = [
    #path('', TemplateView.as_view(template_name="home.html")),
    path('admin/', admin.site.urls),
    path('messages/', include('chat.urls')),
    path('',views.index,name='index'),
    path('special',views.special,name='special'),
    path('session_security', include('session_security.urls')),
    path('logout', views.user_logout, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

"""urlpatterns += [
    path('', RedirectView.as_view(url='/messages/profile', permanent=True)),
]"""

chat/urls.py
from django.urls import path, re_path
from .import views

from .views import ThreadView, InboxView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view(), name='inbox'),
    re_path(r"^(?P<username>[\w.@+-]+)/$", ThreadView.as_view(),name = "chatur1"),
    path('profile',views.profile, name = 'profile'),
    path('register',views.register,name='register'),
    path('user_login',views.user_login,name='user_login'),
    path('user_logout',views.user_logout,name='user_logout'),
]

templates/base1.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
               
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
          <li><a href="{% url 'chat:profile' %}">profile</a></li>
            <li><a href="{% url 'chat:user_logout' %}">Logout</a></li>
          {% else %}
          <li><a class="navbar-link" href="{% url 'chat:register' %}">Register</a></li>  
          <li><a class="navbar-link" href="{% url 'chat:user_login' %}">Login</a></li>

          {% endif %}

</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/css.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

templates/home.html
{% extends "base1.html" %}

{% block content %}

<p>Welcome Home</p>
User List :
{% for u in users %}
<ul>
    {% if user.id != session.uid %}
        <li><a href="/messages/{{u.username}}">{{u.username}}</a>
            {% if user.online != "0" %}
                <span style="height: 12px;width: 12px;background-color: #1fc124;border-radius: 6px;
                float: right;margin-top: 5px;"></span>
            {% else %}
                <span style="height: 12px;width: 12px;background-color: #8a8a8a;border-radius: 6px;
                float: right;margin-top: 5px;"></span>
            {% endif %}
        </li>
    {% endif %}

</ul>
{% endfor %}


    
{% endblock %}

templates/home1.html
{% extends 'base1.html' %}
{% block body_block %}

  <div class="container">
    <div class="jumbotron">
User List :
{% for u in users %}
<ul>
    
        <li><a href="/messages/{{u.username}}">{{u.username}}</a>
            {% for s in status %}
            {% if s.user == u %}
                {% if s.session != 0 %}
                    <span style="height: 12px;width: 12px;background-color: #1fc124;border-radius: 6px;
                    float: right;margin-top: 5px;"></span>
                {% else %}
                    <span style="height: 12px;width: 12px;background-color: #8a8a8a;border-radius: 6px;
                    float: right;margin-top: 5px;"></span>
                {% endif %}
            {% endif %}    
            {% endfor %}
        </li>
    

</ul>
{% endfor %}
    
{% endblock %}

templates/index1.html
{% extends "base1.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Chat App!</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        {% for session in user_sessions %}
          {{session}}<br/>
        {% endfor %}
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

templates/js.html
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
  src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

templates/logged_out.html
{% extends "base1.html" %}

{% block content %}
  <p>Logged out!</p>  
  <a href="{% url 'login'%}">Click here to login again.</a>
{% endblock %}

templates/login.html
{% extends 'base1.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>

<form method="post" action="{% url 'chat:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">

<input type="submit" name="" value="Login">

</form>

</div>
  </div>
{% endblock %}

templates/registration.html
{% extends "base1.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}